### ISSUE TITLE
Change the Repo Name

### ISSUE THREAD

**Issue by dspinosa** [Innovate-Inc/Web-AppBuilder#4]
Please change the repo name from  Web-AppBuilder to Web-AppBuilderWidgets

Update the land landing page content to reflect widgets rather than web app builder.
Update the readme
Update the wiki

**Comment by dwoodinnovate** [comment]
Hey Dan,
    Was this supposed to go to Yarnell? I am not currently working on any
github repo's at the moment to my knowledge. :)

On Mon, Mar 21, 2016 at 9:25 AM, dspinosa <notifications@github.com> wrote:

> Please change the repo name from Web-AppBuilder to Web-AppBuilderWidgets
>
> Update the land landing page content to reflect widgets rather than web
> app builder.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Innovate-Inc/Web-AppBuilder/issues/4>
>



-- 
*Dave Wood*
*Developer - Innovate! Inc. - phone (703) 922 9090 ext.707*

**Comment by David-Yarnell** [comment]
Updates are complete
